version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore ASPServerlessApp/ASPServerlessApp.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output ASPServerlessApp/ASPServerlessApp.csproj
artifacts:
  files:
    - ASPServerlessApp/build_output/**/*
    - scripts/**/*
    - appspec.yml
    - ServerlessTemplate.yml
