version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore ASPServerlessApp/ASPServerlessApp.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release
artifacts:
  files:
    - /**/*
    - scripts/**/*
    - appspec.yml
    - ServerlessTemplate.yml
